### ISSUE TITLE
Priority selector UX problem

### ISSUE THREAD

**Issue by michefraim** [shirameirovitz/pre-course-2021-final-boilerplate#1]
When i open the priority menu, and then i hover off it and back on it, the priorities become blank - white background instead of being able to see the number of the priority.

Steps to reproduce:

1.  open the priority menu.
2. hover the mouse away from it.
3. return the mouse to the selector

**expected result:**
 priority numbers (1-5).

**actual result**
: white blank squares.

**Comment by listguy** [comment]
👌
